---
kind: pipeline
type: exec
name: deploy

platform:
  os: linux
  arch: amd64

workspace:
  path: /data/share/projects/git/Citadel

steps:
- name: mirroring to github
  environment:
    mirror: "git@github.com:pwnlxrd/citadel.git"
    TOKEN:
      from_secret: token
  commands:
  - git push --mirror $${mirror}
  - curl -s -X POST https://api.telegram.org/bot$${TOKEN}/sendMessage -d chat_id=-456374469 -d text="mirroring $${mirror} done 🚀"