version: '3.6'

networks:
  monitor-net:
    driver: bridge
  gitea:
    external: false

# volumes:
#     prometheus_data: {}
#     grafana_data: {}

services:

# step-ca

  step-ca:
    container_name: step-ca
    image: smallstep/step-ca
    restart: unless-stopped
    volumes:
      - /data/containers_data/step-ca:/home/step
    networks:
      - monitor-net
    ports:
      - "9000:9000"
    dns:
      - 192.168.0.125

# traefik
  traefik:
    image: "traefik:latest"
    container_name: "traefik"
    environment:
      LEGO_CA_CERTIFICATES: "/usr/local/share/ca-certificates/pwn-ca-bundle.pem"
    ports:
      - "80:80"
      - "443:443"
    networks:
      - monitor-net
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/usr/local/share/ca-certificates/pwn-ca-bundle.pem:/usr/local/share/ca-certificates/pwn-ca-bundle.pem:ro"
      - "/data/containers_data/traefik/configs/traefik.yml:/traefik.yml:ro"
      - "/data/containers_data/traefik/certs:/letsencrypt"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.entrypoints=websecure"
      - "traefik.http.routers.traefik.rule=Host(`traefik.pwn.dev`)"
      - "traefik.http.routers.traefik.service=api@internal"
      - "traefik.http.routers.traefik.tls=true"
      - "traefik.http.routers.traefik.tls.certresolver=pwn-ca"
      - "traefik.http.middlewares.traefik-auth.basicauth.users=pwnlxrd:${traefik_pass}"
      - "traefik.http.routers.traefik.middlewares=traefik-auth"
    depends_on:
      - "step-ca"

# monitorings service

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - /data/containers_data/prometheus/etc:/etc/prometheus
      - /data/containers_data/prometheus/data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--storage.tsdb.retention.time=200h'
      - '--web.enable-lifecycle'
    restart: unless-stopped
    ports:
      - 9090:9090
    networks:
      - monitor-net
    labels:
      org.label-schema.group: "monitoring"

  blackbox:
    container_name: blackbox
    image: prom/blackbox-exporter
    #ports:
    # - 9115:9115
    networks:
      - monitor-net
    volumes:
      - /data/containers_data/prometheus/etc/blackbox:/etc/blackboxexporter
    command:
      - '--config.file=/etc/blackboxexporter/config.yml'
      - '--log.level=debug'
    restart: always
    labels:
      org.label-schema.group: "monitoring"

  alertmanager:
    image: prom/alertmanager:latest
    container_name: alertmanager
    volumes:
      - /data/containers_data/alertmanager/etc:/etc/alertmanager
    command:
      - '--config.file=/etc/alertmanager/config.yml'
      - '--storage.path=/alertmanager'
    restart: unless-stopped
    ports:
      - 9093:9093
    networks:
      - monitor-net
    labels:
      org.label-schema.group: "monitoring"

  nodeexporter:
    image: prom/node-exporter:latest
    container_name: nodeexporter
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points=^/(sys|proc|dev|host|etc)($$|/)'
    restart: unless-stopped
    ports:
      - 9100:9100
    networks:
      - monitor-net
    labels:
      org.label-schema.group: "monitoring"

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker:/var/lib/docker:ro
      #- /cgroup:/cgroup:ro #doesn't work on MacOS only for Linux
    restart: unless-stopped
    ports:
      - 8080:8080
    networks:
      - monitor-net
    labels:
      org.label-schema.group: "monitoring"

# Grafana

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    volumes:
      - /data/containers_data/grafana/data:/var/lib/grafana
      - /data/containers_data/grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards
      - /data/containers_data/grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
    environment:
      - GF_SECURITY_ADMIN_USER=${ADMIN_USER:-admin}
      - GF_SECURITY_ADMIN_PASSWORD=${ADMIN_PASSWORD:-admin}
      - GF_USERS_ALLOW_SIGN_UP=false
    restart: unless-stopped
    # ports:
    #   - 3011:3000
    networks:
      - monitor-net
    # labels:
    #   org.label-schema.group: "monitoring"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.grafana.rule=Host(`grafana.pwn.dev`)"
      - "traefik.http.routers.grafana.entrypoints=websecure"
      - "traefik.http.routers.grafana.tls.certresolver=pwn-ca"
      - "traefik.http.services.grafana-service.loadbalancer.server.port=3000"

  pushgateway:
    image: prom/pushgateway:v1.4.1
    container_name: pushgateway
    restart: unless-stopped
    ports:
      - 9091:9091
    networks:
      - monitor-net
    labels:
      org.label-schema.group: "monitoring"

# gitea and db

  gitea-db: 
    container_name: postresqlG
    image: postgres:13.5-bullseye
    restart: unless-stopped
    environment:
      - POSTGRES_USER=gitea-admin-db
      - POSTGRES_PASSWORD=${gitea_db_pass}
      - POSTGRES_DB=gitea-db
    networks:
      - monitor-net
    volumes:
      - /data/containers_data/gitea/gitea_data_db:/var/lib/postgresql/data


  gitea:
    image: gitea/gitea:latest
    container_name: gitea
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - DB_TYPE=postgres
      - DB_HOST=gitea-db:5432
      - DB_NAME=gitea-db
      - DB_USER=gitea-admin-db
      - DB_PASSWD=${gitea_db_pass}
    restart: unless-stopped
    networks:
      - monitor-net
    volumes:
      - /data/containers_data/gitea/gitea_data:/data/gitea
      - /data/containers_data/gitea/gitea_repo:/data/git
      - /data/containers_data/gitea/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "223:22"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.gitea.rule=Host(`git.pwn.dev`)"
      - "traefik.http.routers.gitea.entrypoints=websecure"
      - "traefik.http.routers.gitea.tls.certresolver=pwn-ca"
      - "traefik.http.services.gitea-service.loadbalancer.server.port=3000"
    depends_on:
      - gitea-db

#heimdall

  heimdall:
    image: linuxserver/heimdall:latest
    container_name: heimdall
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - /data/containers_data/heimdall/config:/config
    networks:
      - monitor-net
    environment:
      - PGID=1000
      - PUID=1000
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.heimdall.rule=Host(`welcome.pwn.dev`)"
      - "traefik.http.routers.heimdall.entrypoints=websecure"
      - "traefik.http.routers.heimdall.tls.certresolver=pwn-ca"
      - "traefik.http.services.heimdall-service.loadbalancer.server.port=80"

#searx and filter

  filtron:
    container_name: filtron
    image: dalf/filtron
    restart: always
    #ports:
    #  - "127.0.0.1:4040:4040"
    #  - "127.0.0.1:4041:4041"
    networks:
      - monitor-net
    command: -listen 0.0.0.0:4040 -api 0.0.0.0:4041 -target searx:8080
    volumes:
      - /data/containers_data/searx/rules.json:/etc/filtron/rules.json:rw
    read_only: true
    cap_drop:
      - ALL

  searx:
    container_name: searx
    image: searx/searx:latest
    restart: always
    networks:
      - monitor-net
    command: -f
    volumes:
      - /data/containers_data/searx/configs:/etc/searx:rw
    environment:
      - BIND_ADDRESS=0.0.0.0:8080
      - BASE_URL=https://searx.pwn.dev/
      - MORTY_URL=https://searx.pwn.dev/morty/
      - MORTY_KEY=${morty_key_secret}
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
      - DAC_OVERRIDE
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.searx.rule=Host(`searx.pwn.dev`)"
      - "traefik.http.routers.searx.entrypoints=websecure"
      - "traefik.http.routers.searx.tls.certresolver=pwn-ca"
      - "traefik.http.services.searx-service.loadbalancer.server.port=8080"

  morty:
    container_name: morty
    image: dalf/morty
    restart: always
    ports:
      - "127.0.0.1:3000:3000"
    networks:
      - monitor-net
    command: -timeout 6 -ipv6
    environment:
      - MORTY_KEY=${morty_key_secret}
      - MORTY_ADDRESS=0.0.0.0:3000
    #logging:
    #  driver: none
    read_only: true
    cap_drop:
      - ALL

#main dev-server

  dev-server-main:
    container_name: dev-server-main
    image: dev-server:x86
    network_mode: bridge
    volumes:
      - "/home/pwnlxrd/.ssh/authorized_keys:/home/user/.ssh/authorized_keys:ro"
      - /data/share:/data
    ports:
      - "7001:22"
      - "8000:8000"
    restart: unless-stopped

#mail service
  # External dependencies
  redis-mail:
    image: redis:alpine
    restart: always
    networks:
      - monitor-net
    volumes:
      - "/data/containers_data/mailu/redis:/data"
    
  # Core services
  front:
    image: ${DOCKER_ORG:-mailu}/${DOCKER_PREFIX:-}nginx:${MAILU_VERSION:-1.8}
    restart: always
    env_file: .env
    logging:
      driver: json-file
    ports:
      - "127.0.0.1:80:80"
      - "::1:80:80"
      - "127.0.0.1:443:443"
      - "::1:443:443"
      - "127.0.0.1:25:25"
      - "::1:25:25"
      - "127.0.0.1:465:465"
      - "::1:465:465"
      - "127.0.0.1:587:587"
      - "::1:587:587"
      - "127.0.0.1:110:110"
      - "::1:110:110"
      - "127.0.0.1:995:995"
      - "::1:995:995"
      - "127.0.0.1:143:143"
      - "::1:143:143"
      - "127.0.0.1:993:993"
      - "::1:993:993"
    networks:
      - monitor-net
    volumes:
      - "/data/containers_data/mailu/certs:/certs"
      - "/data/containers_data/mailu/overrides/nginx:/overrides:ro"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.gitea.rule=Host(`mail.pwn.dev`)"
      - "traefik.http.routers.gitea.entrypoints=websecure"
      - "traefik.http.routers.gitea.tls.certresolver=pwn-ca"
      - "traefik.http.services.gitea-service.loadbalancer.server.port=443"


  admin:
    image: ${DOCKER_ORG:-mailu}/${DOCKER_PREFIX:-}admin:${MAILU_VERSION:-1.8}
    restart: always
    env_file: .env
    networks:
      - monitor-net
    volumes:
      - "/data/containers_data/mailu/data:/data"
      - "/data/containers_data/mailu/dkim:/dkim"
    depends_on:
      - redis-mail

  imap:
    image: ${DOCKER_ORG:-mailu}/${DOCKER_PREFIX:-}dovecot:${MAILU_VERSION:-1.8}
    restart: always
    env_file: .env
    networks:
      - monitor-net
    volumes:
      - "/data/containers_data/mailu/mail:/mail"
      - "/data/containers_data/mailu/overrides/dovecot:/overrides:ro"
    depends_on:
      - front

  smtp:
    image: ${DOCKER_ORG:-mailu}/${DOCKER_PREFIX:-}postfix:${MAILU_VERSION:-1.8}
    restart: always
    env_file: .env
    networks:
      - monitor-net
    volumes:
      - "/data/containers_data/mailu/mailqueue:/queue"
      - "/data/containers_data/mailu/overrides/postfix:/overrides:ro"
    depends_on:
      - front

  antispam:
    image: ${DOCKER_ORG:-mailu}/${DOCKER_PREFIX:-}rspamd:${MAILU_VERSION:-1.8}
    hostname: antispam
    restart: always
    env_file: .env
    networks:
      - monitor-net
    volumes:
      - "/data/containers_data/mailu/filter:/var/lib/rspamd"
      - "/data/containers_data/mailu/dkim:/dkim:ro"
      - "/data/containers_data/mailu/overrides/rspamd:/etc/rspamd/override.d:ro"
    depends_on:
      - front

  # Optional services
  antivirus:
    image: ${DOCKER_ORG:-mailu}/${DOCKER_PREFIX:-}clamav:${MAILU_VERSION:-1.8}
    restart: always
    env_file: .env
    networks:
      - monitor-net
    volumes:
      - "/data/containers_data/mailu/filter:/data"


  fetchmail:
    image: ${DOCKER_ORG:-mailu}/${DOCKER_PREFIX:-}fetchmail:${MAILU_VERSION:-1.8}
    restart: always
    networks:
      - monitor-net
    env_file: .env

  # Webmail
  webmail:
    image: ${DOCKER_ORG:-mailu}/${DOCKER_PREFIX:-}roundcube:${MAILU_VERSION:-1.8}
    restart: always
    env_file: .env
    networks:
      - monitor-net
    volumes:
      - "/data/containers_data/mailu/webmail:/data"
    depends_on:
      - imap

#drone ci
  drone:
    container_name: drone-server
    image: drone/drone:2
    restart: always
    networks:
      - monitor-net
    volumes:
      - /data/containers_data/drone:/data
    environment:
      - DRONE_GITEA_SERVER=https://git.pwndev.com
      - DRONE_GITEA_CLIENT_ID=${DRONE_GITEA_CLIENT_ID}
      - DRONE_GITEA_CLIENT_SECRET=${DRONE_GITEA_CLIENT_SECRET}
      - DRONE_RPC_SECRET=${DRONE_RPC_SECRET}
      - DRONE_SERVER_HOST=drone-server
      - DRONE_SERVER_PROTO=http
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.drone.rule=Host(`drone.pwn.dev`)"
      - "traefik.http.routers.drone.entrypoints=websecure"
      - "traefik.http.routers.drone.tls.certresolver=pwn-ca"
      - "traefik.http.services.drone-service.loadbalancer.server.port=80"

  drone-runner1:
    container_name: drone-runner-main
    image: drone/drone:1
    restart: always
    networks:
      - monitor-net
    volumes:
      - /data/share/projects:/data-project
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DRONE_RPC_PROTO=http
      - DRONE_RPC_HOST=drone-server
      - DRONE_RPC_SECRET=${DRONE_RPC_SECRET}
      - DRONE_RUNNER_CAPACITY=2
      - DRONE_RUNNER_NAME=main-runner
      - DRONE_GITEA_SERVER=https://git.pwndev.com
      - DRONE_GITEA_CLIENT_ID=${DRONE_GITEA_CLIENT_ID}
      - DRONE_GITEA_CLIENT_SECRET=${DRONE_GITEA_CLIENT_SECRET}